#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata_v2.valuelists as VL

from modtools.gamedata_v2.gamedata import GameData


class CriticalHitTypeData(GameData):
    AcidFX: VL.Guid = VL.Guid
    BludgeoningFX: VL.Guid = VL.Guid
    ColdFX: VL.Guid = VL.Guid
    FireFX: VL.Guid = VL.Guid
    ForceFX: VL.Guid = VL.Guid
    LightningFX: VL.Guid = VL.Guid
    NecroticFX: VL.Guid = VL.Guid
    PiercingFX: VL.Guid = VL.Guid
    PoisonFX: VL.Guid = VL.Guid
    PsychicFX: VL.Guid = VL.Guid
    RadiantFX: VL.Guid = VL.Guid
    SlashingFX: VL.Guid = VL.Guid
    ThunderFX: VL.Guid = VL.Guid
