#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.valuelists_v2 as VL

from modtools.gamedata_v2.gamedata import GameData


class ObjectData(GameData):
    _id_ = "Object"
    AcidResistance: VL.ResistanceFlags = VL.ResistanceFlags
    AddToBottomBar: VL.YesNo = VL.YesNo
    Armor: VL.ConstantInt = VL.ConstantInt
    BludgeoningResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ColdResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ComboCategory: VL.FixedString = VL.FixedString
    DarkvisionRange: VL.ConstantInt = VL.ConstantInt
    DefaultBoosts: VL.FixedString = VL.FixedString
    FOV: VL.ConstantInt = VL.ConstantInt
    FallingHitEffect: VL.FixedString = VL.FixedString
    FallingLandEffect: VL.FixedString = VL.FixedString
    FireResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Flags: VL.AttributeFlags = VL.AttributeFlags
    ForceResistance: VL.ResistanceFlags = VL.ResistanceFlags
    GameSize: VL.FixedString = VL.FixedString
    IgnoredByAI: VL.YesNo = VL.YesNo
    InventoryTab: VL.InventoryTabs = VL.InventoryTabs
    ItemUseType: VL.ItemUseTypes = VL.ItemUseTypes
    Level: VL.ConstantInt = VL.ConstantInt
    LightningResistance: VL.ResistanceFlags = VL.ResistanceFlags
    MaxAmount: VL.ConstantInt = VL.ConstantInt
    MaxLevel: VL.ConstantInt = VL.ConstantInt
    MinAmount: VL.ConstantInt = VL.ConstantInt
    MinLevel: VL.ConstantInt = VL.ConstantInt
    MinimumDetectionRange: VL.ConstantInt = VL.ConstantInt
    NecroticResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ObjectCategory: VL.FixedString = VL.FixedString
    PassivesOnEquip: VL.FixedString = VL.FixedString
    PersonalStatusImmunities: VL.StatusIDs = VL.StatusIDs
    PiercingResistance: VL.ResistanceFlags = VL.ResistanceFlags
    PoisonResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Priority: VL.ConstantInt = VL.ConstantInt
    PsychicResistance: VL.ResistanceFlags = VL.ResistanceFlags
    RadiantResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Rarity: VL.Rarity = VL.Rarity
    Requirements: VL.Requirements = VL.Requirements
    RootTemplate: VL.FixedString = VL.FixedString
    Sight: VL.ConstantInt = VL.ConstantInt
    SlashingResistance: VL.ResistanceFlags = VL.ResistanceFlags
    SoundSize: VL.FixedString = VL.FixedString
    StatusInInventory: VL.FixedString = VL.FixedString
    SupplyValue: VL.ConstantInt = VL.ConstantInt
    ThunderResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Unique: VL.ConstantInt = VL.ConstantInt
    UseConditions: VL.Conditions = VL.Conditions
    UseCosts: VL.FixedString = VL.FixedString
    ValueLevel: VL.ConstantInt = VL.ConstantInt
    ValueOverride: VL.ConstantInt = VL.ConstantInt
    ValueRounding: VL.ConstantInt = VL.ConstantInt
    ValueScale: VL.ConstantFloat = VL.ConstantFloat
    ValueUUID: VL.Guid = VL.Guid
    VerticalFOV: VL.ConstantInt = VL.ConstantInt
    Vitality: VL.ConstantInt = VL.ConstantInt
    Weight: VL.ConstantFloat = VL.ConstantFloat
