#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata_v2.valuelists as VL

from modtools.gamedata_v2.gamedata import GameData


class Weapon(GameData):
    Boosts: VL.FixedString = VL.FixedString
    BoostsOnEquipMainHand: VL.FixedString = VL.FixedString
    BoostsOnEquipOffHand: VL.FixedString = VL.FixedString
    Charges: VL.ConstantInt = VL.ConstantInt
    ColorPresetResource: VL.FixedString = VL.FixedString
    ComboCategory: VL.FixedString = VL.FixedString
    Damage: VL.FixedString = VL.FixedString
    Damage_Range: VL.ConstantInt = VL.ConstantInt
    Damage_Type: VL.DamageType = VL.DamageType
    DefaultBoosts: VL.FixedString = VL.FixedString
    Durability: VL.ConstantInt = VL.ConstantInt
    DurabilityDegradeSpeed: VL.Qualifier = VL.Qualifier
    ExtraProperties: VL.FixedString = VL.FixedString
    FallingHitEffect: VL.FixedString = VL.FixedString
    FallingLandEffect: VL.FixedString = VL.FixedString
    Flags: VL.AttributeFlags = VL.AttributeFlags
    GameSize: VL.FixedString = VL.FixedString
    IgnoreVisionBlock: VL.YesNo = VL.YesNo
    InventoryTab: VL.InventoryTabs = VL.InventoryTabs
    ItemColor: VL.FixedString = VL.FixedString
    ItemGroup: VL.FixedString = VL.FixedString
    Level: VL.ConstantInt = VL.ConstantInt
    MaxAmount: VL.ConstantInt = VL.ConstantInt
    MaxCharges: VL.ConstantInt = VL.ConstantInt
    MaxLevel: VL.ConstantInt = VL.ConstantInt
    MinAmount: VL.ConstantInt = VL.ConstantInt
    MinLevel: VL.ConstantInt = VL.ConstantInt
    NeedsIdentification: VL.YesNo = VL.YesNo
    ObjectCategory: VL.FixedString = VL.FixedString
    PassivesMainHand: VL.FixedString = VL.FixedString
    PassivesOffHand: VL.FixedString = VL.FixedString
    PassivesOnEquip: VL.FixedString = VL.FixedString
    PersonalStatusImmunities: VL.StatusIDs = VL.StatusIDs
    Priority: VL.ConstantInt = VL.ConstantInt
    Proficiency_Group: VL.ProficiencyGroupFlags = VL.ProficiencyGroupFlags
    Projectile: VL.FixedString = VL.FixedString
    Rarity: VL.Rarity = VL.Rarity
    Requirements: VL.Requirements = VL.Requirements
    RootTemplate: VL.FixedString = VL.FixedString
    Slot: VL.Itemslot = VL.Itemslot
    SoundSize: VL.FixedString = VL.FixedString
    Spells: VL.FixedString = VL.FixedString
    StatusInInventory: VL.FixedString = VL.FixedString
    StatusOnEquip: VL.FixedString = VL.FixedString
    SupplyValue: VL.ConstantInt = VL.ConstantInt
    Tags: VL.FixedString = VL.FixedString
    Unique: VL.ConstantInt = VL.ConstantInt
    UniqueWeaponSoundSwitch: VL.FixedString = VL.FixedString
    UseConditions: VL.Conditions = VL.Conditions
    UseCosts: VL.FixedString = VL.FixedString
    ValueLevel: VL.ConstantInt = VL.ConstantInt
    ValueOverride: VL.ConstantInt = VL.ConstantInt
    ValueRounding: VL.ConstantInt = VL.ConstantInt
    ValueScale: VL.ConstantFloat = VL.ConstantFloat
    ValueUUID: VL.Guid = VL.Guid
    VersatileDamage: VL.FixedString = VL.FixedString
    WeaponFunctors: VL.StatsFunctors = VL.StatsFunctors
    WeaponRange: VL.ConstantInt = VL.ConstantInt
    Weapon_Group: VL.WeaponGroup = VL.WeaponGroup
    Weapon_Properties: VL.WeaponFlags = VL.WeaponFlags
    Weight: VL.ConstantFloat = VL.ConstantFloat
