#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

"""
A class representing game data, together with definitions parsed from Modifiers.txt.
"""

import modtools.valuelists_v2 as VL

from collections.abc import Callable, Set
from typing import ClassVar


class GameData:
    """Representation of game data ("Modifiers")."""

    _LIST_TYPES = (list, tuple, set)

    _id_: ClassVar[str]                      # The data's id attribute (defaulting to the subclass name).
    _fields_: ClassVar[dict[str, Set[str]]]  # The data's field definitions.

    name: str
    using: str

    @classmethod
    def __init_subclass__(cls) -> None:
        cls._id_ = str(cls.__dict__.get("_id_", cls.__name__))
        cls._fields_ = dict()

        for member_name, value in list(cls.__dict__.items()):
            if value in VL.VALUELISTS:
                cls._fields_[member_name.replace(" ", "_")] = value

        for member_name in cls._fields_:
            getter, setter = cls._wrap_accessors(member_name)
            prop = property(fget=getter, fset=setter)
            setattr(cls, member_name, prop)

    def __init__(self, name: str, **kwds):
        self.name = name
        self.using = None

        for key, value in kwds.items():
            setattr(self, key, value)

    def __str__(self) -> str:
        """Returns a game data string."""
        s = f"new entry \"{self.name}\"\n"
        s += f"type \"{self._id_}\"\n"
        if self.using:
            s += f"using \"{self.using}\"\n"
        for key in self._fields_.keys():
            if (values := getattr(self, key, None)) is not None:
                if len(values) == 1:
                    values = values[0]
                else:
                    values = ";".join(values)
                s += f"data \"{key.replace("_", " ")}\" \"{values}\"\n"
        return s

    @classmethod
    def _wrap_accessors(cls, member_name: str) -> tuple[Callable[[object], any],
                                                        Callable[[object, any], None]]:
        private_member = "_" + member_name
        member_type = cls._fields_[member_name]

        def getter(obj: object) -> list[str] | None:
            return obj.__dict__.get(private_member)

        def setter(obj: object, values: list[str] | None) -> None:
            if values is not None:
                if not isinstance(values, cls._LIST_TYPES):
                    values = [value for value in str(values).split(";") if value]
                values = [str(member_type(value)) for value in values]
            obj.__dict__[private_member] = values

        return (getter, setter)


class Armor(GameData):
    Ability_Modifier_Cap: VL.ConstantInt = VL.ConstantInt
    ArmorClass: VL.ConstantInt = VL.ConstantInt
    ArmorType: VL.ArmorType = VL.ArmorType
    Armor_Class_Ability: VL.Ability = VL.Ability
    Boosts: VL.FixedString = VL.FixedString
    Charges: VL.ConstantInt = VL.ConstantInt
    ColorPresetResource: VL.FixedString = VL.FixedString
    ComboCategory: VL.FixedString = VL.FixedString
    DefaultBoosts: VL.FixedString = VL.FixedString
    Durability: VL.ConstantInt = VL.ConstantInt
    DurabilityDegradeSpeed: VL.Qualifier = VL.Qualifier
    ExtraProperties: VL.FixedString = VL.FixedString
    FallingHitEffect: VL.FixedString = VL.FixedString
    FallingLandEffect: VL.FixedString = VL.FixedString
    Flags: VL.AttributeFlags = VL.AttributeFlags
    GameSize: VL.FixedString = VL.FixedString
    InstrumentType: VL.InstrumentType = VL.InstrumentType
    InventoryTab: VL.InventoryTabs = VL.InventoryTabs
    ItemColor: VL.FixedString = VL.FixedString
    ItemGroup: VL.FixedString = VL.FixedString
    Level: VL.ConstantInt = VL.ConstantInt
    MaxAmount: VL.ConstantInt = VL.ConstantInt
    MaxCharges: VL.ConstantInt = VL.ConstantInt
    MaxLevel: VL.ConstantInt = VL.ConstantInt
    MinAmount: VL.ConstantInt = VL.ConstantInt
    MinLevel: VL.ConstantInt = VL.ConstantInt
    NeedsIdentification: VL.YesNo = VL.YesNo
    ObjectCategory: VL.FixedString = VL.FixedString
    PassivesOnEquip: VL.FixedString = VL.FixedString
    PersonalStatusImmunities: VL.StatusIDs = VL.StatusIDs
    Priority: VL.ConstantInt = VL.ConstantInt
    Proficiency_Group: VL.ProficiencyGroupFlags = VL.ProficiencyGroupFlags
    Rarity: VL.Rarity = VL.Rarity
    Requirements: VL.Requirements = VL.Requirements
    RootTemplate: VL.FixedString = VL.FixedString
    Shield: VL.YesNo = VL.YesNo
    Slot: VL.Itemslot = VL.Itemslot
    SoundSize: VL.FixedString = VL.FixedString
    Spells: VL.FixedString = VL.FixedString
    StatusInInventory: VL.FixedString = VL.FixedString
    StatusOnEquip: VL.FixedString = VL.FixedString
    Tags: VL.FixedString = VL.FixedString
    Unique: VL.ConstantInt = VL.ConstantInt
    UseConditions: VL.Conditions = VL.Conditions
    UseCosts: VL.FixedString = VL.FixedString
    ValueLevel: VL.ConstantInt = VL.ConstantInt
    ValueOverride: VL.ConstantInt = VL.ConstantInt
    ValueRounding: VL.ConstantInt = VL.ConstantInt
    ValueScale: VL.ConstantFloat = VL.ConstantFloat
    ValueUUID: VL.Guid = VL.Guid
    Weight: VL.ConstantFloat = VL.ConstantFloat


class Character(GameData):
    AcidResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ActionResources: VL.FixedString = VL.FixedString
    Armor: VL.ConstantInt = VL.ConstantInt
    ArmorType: VL.ArmorType = VL.ArmorType
    BludgeoningResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Charisma: VL.ConstantInt = VL.ConstantInt
    Class: VL.FixedString = VL.FixedString
    ColdResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Constitution: VL.ConstantInt = VL.ConstantInt
    DarkvisionRange: VL.FixedString = VL.FixedString
    DefaultBoosts: VL.FixedString = VL.FixedString
    Dexterity: VL.ConstantInt = VL.ConstantInt
    DifficultyStatuses: VL.FixedString = VL.FixedString
    DynamicAnimationTag: VL.Guid = VL.Guid
    ExtraProperties: VL.FixedString = VL.FixedString
    FOV: VL.ConstantInt = VL.ConstantInt
    FallingHitEffect: VL.FixedString = VL.FixedString
    FallingLandEffect: VL.FixedString = VL.FixedString
    FireResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Flags: VL.AttributeFlags = VL.AttributeFlags
    ForceResistance: VL.ResistanceFlags = VL.ResistanceFlags
    GameSize: VL.FixedString = VL.FixedString
    Hearing: VL.ConstantInt = VL.ConstantInt
    Initiative: VL.ConstantInt = VL.ConstantInt
    Intelligence: VL.ConstantInt = VL.ConstantInt
    Level: VL.ConstantInt = VL.ConstantInt
    LightningResistance: VL.ResistanceFlags = VL.ResistanceFlags
    MinimumDetectionRange: VL.FixedString = VL.FixedString
    NecroticResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Passives: VL.FixedString = VL.FixedString
    PathInfluence: VL.FixedString = VL.FixedString
    PersonalStatusImmunities: VL.StatusIDs = VL.StatusIDs
    PiercingResistance: VL.ResistanceFlags = VL.ResistanceFlags
    PoisonResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ProficiencyBonus: VL.ConstantInt = VL.ConstantInt
    ProficiencyBonusScaling: VL.Guid = VL.Guid
    Proficiency_Group: VL.ProficiencyGroupFlags = VL.ProficiencyGroupFlags
    Progression_Type: VL.ProgressionType = VL.ProgressionType
    Progressions: VL.FixedString = VL.FixedString
    PsychicResistance: VL.ResistanceFlags = VL.ResistanceFlags
    RadiantResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Sight: VL.ConstantInt = VL.ConstantInt
    SlashingResistance: VL.ResistanceFlags = VL.ResistanceFlags
    SoundSize: VL.FixedString = VL.FixedString
    SpellCastingAbility: VL.Ability = VL.Ability
    StepsType: VL.StepsType = VL.StepsType
    Strength: VL.ConstantInt = VL.ConstantInt
    ThunderResistance: VL.ResistanceFlags = VL.ResistanceFlags
    UnarmedAttackAbility: VL.Ability = VL.Ability
    UnarmedRangedAttackAbility: VL.Ability = VL.Ability
    VerticalFOV: VL.ConstantInt = VL.ConstantInt
    Vitality: VL.ConstantInt = VL.ConstantInt
    Weight: VL.ConstantFloat = VL.ConstantFloat
    Wisdom: VL.ConstantInt = VL.ConstantInt
    XPReward: VL.Guid = VL.Guid


class CriticalHitTypeData(GameData):
    AcidFX: VL.Guid = VL.Guid
    BludgeoningFX: VL.Guid = VL.Guid
    ColdFX: VL.Guid = VL.Guid
    FireFX: VL.Guid = VL.Guid
    ForceFX: VL.Guid = VL.Guid
    LightningFX: VL.Guid = VL.Guid
    NecroticFX: VL.Guid = VL.Guid
    PiercingFX: VL.Guid = VL.Guid
    PoisonFX: VL.Guid = VL.Guid
    PsychicFX: VL.Guid = VL.Guid
    RadiantFX: VL.Guid = VL.Guid
    SlashingFX: VL.Guid = VL.Guid
    ThunderFX: VL.Guid = VL.Guid


class InterruptData(GameData):
    Conditions: VL.Conditions = VL.Conditions
    Container: VL.FixedString = VL.FixedString
    Cooldown: VL.CooldownType = VL.CooldownType
    Cost: VL.FixedString = VL.FixedString
    Description: VL.TranslatedString = VL.TranslatedString
    DescriptionParams: VL.FixedString = VL.FixedString
    DescriptionRef: VL.TranslatedString = VL.TranslatedString
    DisplayName: VL.TranslatedString = VL.TranslatedString
    DisplayNameRef: VL.TranslatedString = VL.TranslatedString
    EnableCondition: VL.Conditions = VL.Conditions
    EnableContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ExtraDescription: VL.TranslatedString = VL.TranslatedString
    ExtraDescriptionParams: VL.FixedString = VL.FixedString
    ExtraDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Failure: VL.StatsFunctors = VL.StatsFunctors
    Icon: VL.FixedString = VL.FixedString
    InterruptContext: VL.InterruptContext = VL.InterruptContext
    InterruptContextScope: VL.InterruptContextScope = VL.InterruptContextScope
    InterruptDefaultValue: VL.InterruptDefaultValue = VL.InterruptDefaultValue
    InterruptFlags: VL.InterruptFlagsList = VL.InterruptFlagsList
    LoreDescription: VL.TranslatedString = VL.TranslatedString
    LoreDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Properties: VL.StatsFunctors = VL.StatsFunctors
    Roll: VL.Conditions = VL.Conditions
    ShortDescription: VL.TranslatedString = VL.TranslatedString
    ShortDescriptionParams: VL.FixedString = VL.FixedString
    ShortDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Stack: VL.FixedString = VL.FixedString
    Success: VL.StatsFunctors = VL.StatsFunctors
    TooltipAttackSave: VL.FixedString = VL.FixedString
    TooltipDamageList: VL.FixedString = VL.FixedString
    TooltipOnMiss: VL.FixedString = VL.FixedString
    TooltipOnSave: VL.FixedString = VL.FixedString
    TooltipPermanentWarnings: VL.FixedString = VL.FixedString
    TooltipStatusApply: VL.FixedString = VL.FixedString


class ObjectData(GameData):
    _id_ = "Object"
    AcidResistance: VL.ResistanceFlags = VL.ResistanceFlags
    AddToBottomBar: VL.YesNo = VL.YesNo
    Armor: VL.ConstantInt = VL.ConstantInt
    BludgeoningResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ColdResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ComboCategory: VL.FixedString = VL.FixedString
    DarkvisionRange: VL.ConstantInt = VL.ConstantInt
    DefaultBoosts: VL.FixedString = VL.FixedString
    FOV: VL.ConstantInt = VL.ConstantInt
    FallingHitEffect: VL.FixedString = VL.FixedString
    FallingLandEffect: VL.FixedString = VL.FixedString
    FireResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Flags: VL.AttributeFlags = VL.AttributeFlags
    ForceResistance: VL.ResistanceFlags = VL.ResistanceFlags
    GameSize: VL.FixedString = VL.FixedString
    IgnoredByAI: VL.YesNo = VL.YesNo
    InventoryTab: VL.InventoryTabs = VL.InventoryTabs
    ItemUseType: VL.ItemUseTypes = VL.ItemUseTypes
    Level: VL.ConstantInt = VL.ConstantInt
    LightningResistance: VL.ResistanceFlags = VL.ResistanceFlags
    MaxAmount: VL.ConstantInt = VL.ConstantInt
    MaxLevel: VL.ConstantInt = VL.ConstantInt
    MinAmount: VL.ConstantInt = VL.ConstantInt
    MinLevel: VL.ConstantInt = VL.ConstantInt
    MinimumDetectionRange: VL.ConstantInt = VL.ConstantInt
    NecroticResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ObjectCategory: VL.FixedString = VL.FixedString
    PassivesOnEquip: VL.FixedString = VL.FixedString
    PersonalStatusImmunities: VL.StatusIDs = VL.StatusIDs
    PiercingResistance: VL.ResistanceFlags = VL.ResistanceFlags
    PoisonResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Priority: VL.ConstantInt = VL.ConstantInt
    PsychicResistance: VL.ResistanceFlags = VL.ResistanceFlags
    RadiantResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Rarity: VL.Rarity = VL.Rarity
    Requirements: VL.Requirements = VL.Requirements
    RootTemplate: VL.FixedString = VL.FixedString
    Sight: VL.ConstantInt = VL.ConstantInt
    SlashingResistance: VL.ResistanceFlags = VL.ResistanceFlags
    SoundSize: VL.FixedString = VL.FixedString
    StatusInInventory: VL.FixedString = VL.FixedString
    SupplyValue: VL.ConstantInt = VL.ConstantInt
    ThunderResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Unique: VL.ConstantInt = VL.ConstantInt
    UseConditions: VL.Conditions = VL.Conditions
    UseCosts: VL.FixedString = VL.FixedString
    ValueLevel: VL.ConstantInt = VL.ConstantInt
    ValueOverride: VL.ConstantInt = VL.ConstantInt
    ValueRounding: VL.ConstantInt = VL.ConstantInt
    ValueScale: VL.ConstantFloat = VL.ConstantFloat
    ValueUUID: VL.Guid = VL.Guid
    VerticalFOV: VL.ConstantInt = VL.ConstantInt
    Vitality: VL.ConstantInt = VL.ConstantInt
    Weight: VL.ConstantFloat = VL.ConstantFloat


class PassiveData(GameData):
    BoostConditions: VL.Conditions = VL.Conditions
    BoostContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    Boosts: VL.FixedString = VL.FixedString
    Conditions: VL.Conditions = VL.Conditions
    Description: VL.TranslatedString = VL.TranslatedString
    DescriptionParams: VL.FixedString = VL.FixedString
    DescriptionRef: VL.TranslatedString = VL.TranslatedString
    DisplayName: VL.TranslatedString = VL.TranslatedString
    DisplayNameRef: VL.TranslatedString = VL.TranslatedString
    DynamicAnimationTag: VL.Guid = VL.Guid
    EnabledConditions: VL.Conditions = VL.Conditions
    EnabledContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ExtraDescription: VL.TranslatedString = VL.TranslatedString
    ExtraDescriptionParams: VL.FixedString = VL.FixedString
    ExtraDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Icon: VL.FixedString = VL.FixedString
    LoreDescription: VL.TranslatedString = VL.TranslatedString
    LoreDescriptionRef: VL.TranslatedString = VL.TranslatedString
    PriorityOrder: VL.ConstantInt = VL.ConstantInt
    Properties: VL.PassiveFlags = VL.PassiveFlags
    StatsFunctorContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    StatsFunctors: VL.StatsFunctors = VL.StatsFunctors
    ToggleGroup: VL.FixedString = VL.FixedString
    ToggleOffContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ToggleOffEffect: VL.FixedString = VL.FixedString
    ToggleOffFunctors: VL.StatsFunctors = VL.StatsFunctors
    ToggleOnEffect: VL.FixedString = VL.FixedString
    ToggleOnFunctors: VL.StatsFunctors = VL.StatsFunctors
    TooltipConditionalDamage: VL.FixedString = VL.FixedString
    TooltipPermanentWarnings: VL.FixedString = VL.FixedString
    TooltipSave: VL.FixedString = VL.FixedString
    TooltipUseCosts: VL.FixedString = VL.FixedString


class SpellData(GameData):
    AIFlags: VL.AIFlags = VL.AIFlags
    Acceleration: VL.ConstantInt = VL.ConstantInt
    AddRangeFromAbility: VL.FixedString = VL.FixedString
    AiCalculationSpellOverride: VL.FixedString = VL.FixedString
    AlternativeCastTextEvents: VL.FixedString = VL.FixedString
    AmountOfTargets: VL.FixedString = VL.FixedString
    Angle: VL.ConstantInt = VL.ConstantInt
    AoEConditions: VL.TargetConditions = VL.TargetConditions
    AreaRadius: VL.ConstantInt = VL.ConstantInt
    Autocast: VL.YesNo = VL.YesNo
    Base: VL.ConstantInt = VL.ConstantInt
    BeamEffect: VL.FixedString = VL.FixedString
    CastEffect: VL.FixedString = VL.FixedString
    CastEffectTextEvent: VL.FixedString = VL.FixedString
    CastSound: VL.FixedString = VL.FixedString
    CastTargetHitDelay: VL.ConstantInt = VL.ConstantInt
    CastTextEvent: VL.FixedString = VL.FixedString
    CinematicArenaFlags: VL.CinematicArenaFlags = VL.CinematicArenaFlags
    CinematicArenaTimelineOverride: VL.Guid = VL.Guid
    CombatAIOverrideSpell: VL.FixedString = VL.FixedString
    ConcentrationSpellID: VL.FixedString = VL.FixedString
    ContainerSpells: VL.FixedString = VL.FixedString
    Cooldown: VL.CooldownType = VL.CooldownType
    CycleConditions: VL.TargetConditions = VL.TargetConditions
    Damage: VL.FixedString = VL.FixedString
    DamageType: VL.DamageType = VL.DamageType
    Damage_Range: VL.ConstantInt = VL.ConstantInt
    DeathType: VL.DeathType = VL.DeathType
    DelayRollDie: VL.DieType = VL.DieType
    DelayRollTarget: VL.ConstantInt = VL.ConstantInt
    DelayTurnsCount: VL.ConstantInt = VL.ConstantInt
    Description: VL.TranslatedString = VL.TranslatedString
    DescriptionParams: VL.FixedString = VL.FixedString
    DescriptionRef: VL.TranslatedString = VL.TranslatedString
    DisappearEffect: VL.FixedString = VL.FixedString
    DisplayName: VL.TranslatedString = VL.TranslatedString
    DisplayNameRef: VL.TranslatedString = VL.TranslatedString
    Distribution: VL.ProjectileDistribution = VL.ProjectileDistribution
    DualWieldingSpellAnimation: VL.FixedString = VL.FixedString
    DualWieldingUseCosts: VL.FixedString = VL.FixedString
    EndPosRadius: VL.ConstantInt = VL.ConstantInt
    ExplodeRadius: VL.ConstantInt = VL.ConstantInt
    ExtraDescription: VL.TranslatedString = VL.TranslatedString
    ExtraDescriptionParams: VL.FixedString = VL.FixedString
    ExtraDescriptionRef: VL.TranslatedString = VL.TranslatedString
    FXScale: VL.ConstantInt = VL.ConstantInt
    FemaleImpactEffects: VL.FixedString = VL.FixedString
    FollowUpOriginalSpell: VL.FixedString = VL.FixedString
    ForceTarget: VL.ConstantInt = VL.ConstantInt
    ForkChance: VL.ConstantInt = VL.ConstantInt
    ForkLevels: VL.ConstantInt = VL.ConstantInt
    ForkingConditions: VL.TargetConditions = VL.TargetConditions
    FrontOffset: VL.ConstantInt = VL.ConstantInt
    Height: VL.ConstantInt = VL.ConstantInt
    HighlightConditions: VL.TargetConditions = VL.TargetConditions
    HitAnimationType: VL.HitAnimationType = VL.HitAnimationType
    HitCosts: VL.FixedString = VL.FixedString
    HitDelay: VL.ConstantInt = VL.ConstantInt
    HitEffect: VL.FixedString = VL.FixedString
    HitExtension: VL.ConstantFloat = VL.ConstantFloat
    HitRadius: VL.ConstantFloat = VL.ConstantFloat
    Icon: VL.FixedString = VL.FixedString
    IgnoreTeleport: VL.YesNo = VL.YesNo
    ImpactEffect: VL.FixedString = VL.FixedString
    InstrumentComponentCastSound: VL.FixedString = VL.FixedString
    InstrumentComponentImpactSound: VL.FixedString = VL.FixedString
    InstrumentComponentLoopingSound: VL.FixedString = VL.FixedString
    InstrumentComponentPrepareSound: VL.FixedString = VL.FixedString
    InterruptPrototype: VL.FixedString = VL.FixedString
    ItemWall: VL.FixedString = VL.FixedString
    ItemWallStatus: VL.FixedString = VL.FixedString
    JumpDelay: VL.ConstantInt = VL.ConstantInt
    Level: VL.ConstantInt = VL.ConstantInt
    Lifetime: VL.ConstantInt = VL.ConstantInt
    LineOfSightFlags: VL.LineOfSightFlags = VL.LineOfSightFlags
    Magic_Cost: VL.ConstantInt = VL.ConstantInt
    MaleImpactEffects: VL.FixedString = VL.FixedString
    MaxAttacks: VL.ConstantInt = VL.ConstantInt
    MaxDistance: VL.ConstantInt = VL.ConstantInt
    MaxForkCount: VL.ConstantInt = VL.ConstantInt
    MaxHitsPerTurn: VL.ConstantInt = VL.ConstantInt
    MaximumTargets: VL.ConstantInt = VL.ConstantInt
    MaximumTotalTargetHP: VL.ConstantInt = VL.ConstantInt
    MemorizationRequirements: VL.MemorizationRequirements = VL.MemorizationRequirements
    MemoryCost: VL.ConstantInt = VL.ConstantInt
    Memory_Cost: VL.ConstantInt = VL.ConstantInt
    MinHitsPerTurn: VL.ConstantInt = VL.ConstantInt
    MinJumpDistance: VL.ConstantFloat = VL.ConstantFloat
    MovementSpeed: VL.ConstantInt = VL.ConstantInt
    MovingObjectSummonTemplate: VL.FixedString = VL.FixedString
    NextAttackChance: VL.ConstantInt = VL.ConstantInt
    NextAttackChanceDivider: VL.ConstantInt = VL.ConstantInt
    OnlyHit1Target: VL.ConstantInt = VL.ConstantInt
    OriginSpellFail: VL.StatsFunctors = VL.StatsFunctors
    OriginSpellProperties: VL.StatsFunctors = VL.StatsFunctors
    OriginSpellRoll: VL.RollConditions = VL.RollConditions
    OriginSpellSuccess: VL.StatsFunctors = VL.StatsFunctors
    OriginTargetConditions: VL.TargetConditions = VL.TargetConditions
    OverrideSpellLevel: VL.YesNo = VL.YesNo
    PositionEffect: VL.FixedString = VL.FixedString
    PowerLevel: VL.ConstantInt = VL.ConstantInt
    PrepareEffect: VL.FixedString = VL.FixedString
    PrepareEffectBone: VL.FixedString = VL.FixedString
    PrepareLoopSound: VL.FixedString = VL.FixedString
    PrepareSound: VL.FixedString = VL.FixedString
    PreviewCursor: VL.CursorMode = VL.CursorMode
    PreviewEffect: VL.FixedString = VL.FixedString
    PreviewStrikeHits: VL.YesNo = VL.YesNo
    ProjectileCount: VL.FixedString = VL.FixedString
    ProjectileDelay: VL.ConstantInt = VL.ConstantInt
    ProjectileSpells: VL.FixedString = VL.FixedString
    ProjectileTerrainOffset: VL.YesNo = VL.YesNo
    ProjectileType: VL.ProjectileType = VL.ProjectileType
    Range: VL.ConstantInt = VL.ConstantInt
    ReappearEffect: VL.FixedString = VL.FixedString
    ReappearEffectTextEvent: VL.FixedString = VL.FixedString
    RechargeValues: VL.FixedString = VL.FixedString
    Requirement: VL.SpellRequirement = VL.SpellRequirement
    RequirementConditions: VL.TargetConditions = VL.TargetConditions
    RequirementEvents: VL.StatusEvent = VL.StatusEvent
    Requirements: VL.Requirements = VL.Requirements
    RitualCosts: VL.FixedString = VL.FixedString
    RootSpellID: VL.FixedString = VL.FixedString
    SelectedCharacterEffect: VL.FixedString = VL.FixedString
    SelectedObjectEffect: VL.FixedString = VL.FixedString
    SelectedPositionEffect: VL.FixedString = VL.FixedString
    Shape: VL.FixedString = VL.FixedString
    Sheathing: VL.SpellSheathing = VL.SpellSheathing
    ShortDescription: VL.TranslatedString = VL.TranslatedString
    ShortDescriptionParams: VL.FixedString = VL.FixedString
    ShortDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Shuffle: VL.YesNo = VL.YesNo
    SingleSource: VL.YesNo = VL.YesNo
    SourceLimbIndex: VL.ConstantInt = VL.ConstantInt
    SpawnEffect: VL.FixedString = VL.FixedString
    SpellActionType: VL.SpellActionType = VL.SpellActionType
    SpellActionTypePriority: VL.ConstantInt = VL.ConstantInt
    SpellAnimation: VL.FixedString = VL.FixedString
    SpellAnimationIntentType: VL.SpellAnimationIntentType = VL.SpellAnimationIntentType
    SpellAnimationType: VL.SpellAnimationType = VL.SpellAnimationType
    SpellCategory: VL.SpellCategoryFlags = VL.SpellCategoryFlags
    SpellContainerID: VL.FixedString = VL.FixedString
    SpellEffect: VL.FixedString = VL.FixedString
    SpellFail: VL.StatsFunctors = VL.StatsFunctors
    SpellFlags: VL.SpellFlagList = VL.SpellFlagList
    SpellJumpType: VL.SpellJumpType = VL.SpellJumpType
    SpellProperties: VL.StatsFunctors = VL.StatsFunctors
    SpellRoll: VL.RollConditions = VL.RollConditions
    SpellSchool: VL.SpellSchool = VL.SpellSchool
    SpellSoundAftermathTrajectory: VL.FixedString = VL.FixedString
    SpellSoundMagnitude: VL.SpellSoundMagnitude = VL.SpellSoundMagnitude
    SpellStyleGroup: VL.SpellStyleGroup = VL.SpellStyleGroup
    SpellSuccess: VL.StatsFunctors = VL.StatsFunctors
    SpellType: VL.FixedString = VL.FixedString
    Spellbook: VL.FixedString = VL.FixedString
    Stealth: VL.YesNo = VL.YesNo
    SteerSpeedMultipler: VL.ConstantFloat = VL.ConstantFloat
    StopAtFirstContact: VL.ConstantInt = VL.ConstantInt
    StormEffect: VL.FixedString = VL.FixedString
    StrikeCount: VL.ConstantInt = VL.ConstantInt
    SurfaceGrowInterval: VL.ConstantInt = VL.ConstantInt
    SurfaceGrowStep: VL.ConstantInt = VL.ConstantInt
    SurfaceLifetime: VL.ConstantInt = VL.ConstantInt
    SurfaceRadius: VL.ConstantInt = VL.ConstantInt
    SurfaceType: VL.SurfaceType = VL.SurfaceType
    TargetCeiling: VL.FixedString = VL.FixedString
    TargetConditions: VL.TargetConditions = VL.TargetConditions
    TargetEffect: VL.FixedString = VL.FixedString
    TargetFloor: VL.FixedString = VL.FixedString
    TargetGroundEffect: VL.FixedString = VL.FixedString
    TargetHitEffect: VL.FixedString = VL.FixedString
    TargetProjectiles: VL.YesNo = VL.YesNo
    TargetRadius: VL.FixedString = VL.FixedString
    TargetSound: VL.FixedString = VL.FixedString
    TeleportDelay: VL.ConstantInt = VL.ConstantInt
    TeleportSelf: VL.YesNo = VL.YesNo
    TeleportSurface: VL.YesNo = VL.YesNo
    Template: VL.FixedString = VL.FixedString
    ThrowOrigin: VL.ThrowOrigin = VL.ThrowOrigin
    ThrowableSpellFail: VL.StatsFunctors = VL.StatsFunctors
    ThrowableSpellProperties: VL.StatsFunctors = VL.StatsFunctors
    ThrowableSpellRoll: VL.RollConditions = VL.RollConditions
    ThrowableSpellSuccess: VL.StatsFunctors = VL.StatsFunctors
    ThrowableTargetConditions: VL.TargetConditions = VL.TargetConditions
    TooltipAttackSave: VL.FixedString = VL.FixedString
    TooltipDamageList: VL.FixedString = VL.FixedString
    TooltipOnMiss: VL.FixedString = VL.FixedString
    TooltipOnSave: VL.FixedString = VL.FixedString
    TooltipPermanentWarnings: VL.FixedString = VL.FixedString
    TooltipSpellDCAbilities: VL.AbilityFlags = VL.AbilityFlags
    TooltipStatusApply: VL.FixedString = VL.FixedString
    TooltipUpcastDescription: VL.Guid = VL.Guid
    TooltipUpcastDescriptionParams: VL.FixedString = VL.FixedString
    Trajectories: VL.FixedString = VL.FixedString
    UseCosts: VL.FixedString = VL.FixedString
    UseWeaponDamage: VL.YesNo = VL.YesNo
    UseWeaponProperties: VL.YesNo = VL.YesNo
    VerbalIntent: VL.VerbalIntent = VL.VerbalIntent
    VocalComponentSound: VL.FixedString = VL.FixedString
    WallEndEffect: VL.FixedString = VL.FixedString
    WallStartEffect: VL.FixedString = VL.FixedString
    WeaponBones: VL.FixedString = VL.FixedString
    WeaponTypes: VL.WeaponFlags = VL.WeaponFlags


class StatusData(GameData):
    AbsorbSurfaceRange: VL.ConstantInt = VL.ConstantInt
    AbsorbSurfaceType: VL.FixedString = VL.FixedString
    AiCalculationSpellOverride: VL.FixedString = VL.FixedString
    AnimationEnd: VL.FixedString = VL.FixedString
    AnimationLoop: VL.FixedString = VL.FixedString
    AnimationStart: VL.FixedString = VL.FixedString
    ApplyEffect: VL.FixedString = VL.FixedString
    AuraFX: VL.FixedString = VL.FixedString
    AuraFlags: VL.AuraFlags = VL.AuraFlags
    AuraRadius: VL.ConstantInt = VL.ConstantInt
    AuraStatuses: VL.StatsFunctors = VL.StatsFunctors
    BeamEffect: VL.FixedString = VL.FixedString
    BonusFromSkill: VL.Skill = VL.Skill
    Boosts: VL.FixedString = VL.FixedString
    Charges: VL.ConstantInt = VL.ConstantInt
    DefendTargetPosition: VL.YesNo = VL.YesNo
    Description: VL.TranslatedString = VL.TranslatedString
    DescriptionParams: VL.FixedString = VL.FixedString
    DescriptionRef: VL.TranslatedString = VL.TranslatedString
    DieAction: VL.FixedString = VL.FixedString
    DisableInteractions: VL.YesNo = VL.YesNo
    DisplayName: VL.TranslatedString = VL.TranslatedString
    DisplayNameRef: VL.TranslatedString = VL.TranslatedString
    DynamicAnimationTag: VL.Guid = VL.Guid
    EndEffect: VL.FixedString = VL.FixedString
    ForceStackOverwrite: VL.YesNo = VL.YesNo
    FormatColor: VL.FormatStringColor = VL.FormatStringColor
    FreezeTime: VL.ConstantInt = VL.ConstantInt
    HealEffectId: VL.FixedString = VL.FixedString
    HealMultiplier: VL.ConstantInt = VL.ConstantInt
    HealStat: VL.StatusHealType = VL.StatusHealType
    HealType: VL.HealValueType = VL.HealValueType
    HealValue: VL.FixedString = VL.FixedString
    HideOverheadUI: VL.ConstantInt = VL.ConstantInt
    HitAnimationType: VL.HitAnimationType = VL.HitAnimationType
    Icon: VL.FixedString = VL.FixedString
    ImmuneFlag: VL.AttributeFlags = VL.AttributeFlags
    Instant: VL.YesNo = VL.YesNo
    IsUnique: VL.ConstantInt = VL.ConstantInt
    Items: VL.FixedString = VL.FixedString
    LEDEffect: VL.LEDEffectType = VL.LEDEffectType
    LeaveAction: VL.FixedString = VL.FixedString
    ManagedStatusEffectGroup: VL.FixedString = VL.FixedString
    ManagedStatusEffectType: VL.ManagedStatusEffectType = VL.ManagedStatusEffectType
    Material: VL.FixedString = VL.FixedString
    MaterialApplyArmor: VL.YesNo = VL.YesNo
    MaterialApplyBody: VL.YesNo = VL.YesNo
    MaterialApplyNormalMap: VL.YesNo = VL.YesNo
    MaterialApplyWeapon: VL.YesNo = VL.YesNo
    MaterialFadeAmount: VL.ConstantInt = VL.ConstantInt
    MaterialOverlayOffset: VL.ConstantInt = VL.ConstantInt
    MaterialParameters: VL.FixedString = VL.FixedString
    MaterialType: VL.MaterialType = VL.MaterialType
    MeshEffect: VL.FixedString = VL.FixedString
    Necromantic: VL.YesNo = VL.YesNo
    NumStableFailed: VL.ConstantInt = VL.ConstantInt
    NumStableSuccess: VL.ConstantInt = VL.ConstantInt
    OnApplyConditions: VL.Conditions = VL.Conditions
    OnApplyFail: VL.StatsFunctors = VL.StatsFunctors
    OnApplyFunctors: VL.StatsFunctors = VL.StatsFunctors
    OnApplyRoll: VL.Conditions = VL.Conditions
    OnApplySuccess: VL.StatsFunctors = VL.StatsFunctors
    OnRemoveFail: VL.StatsFunctors = VL.StatsFunctors
    OnRemoveFunctors: VL.StatsFunctors = VL.StatsFunctors
    OnRemoveRoll: VL.Conditions = VL.Conditions
    OnRemoveSuccess: VL.StatsFunctors = VL.StatsFunctors
    OnRollsFailed: VL.StatsFunctors = VL.StatsFunctors
    OnSuccess: VL.StatsFunctors = VL.StatsFunctors
    OnTickFail: VL.StatsFunctors = VL.StatsFunctors
    OnTickRoll: VL.Conditions = VL.Conditions
    OnTickSuccess: VL.StatsFunctors = VL.StatsFunctors
    Passives: VL.FixedString = VL.FixedString
    PeaceOnly: VL.YesNo = VL.YesNo
    PerformEventName: VL.FixedString = VL.FixedString
    PlayerHasTag: VL.FixedString = VL.FixedString
    PlayerSameParty: VL.YesNo = VL.YesNo
    PolymorphResult: VL.FixedString = VL.FixedString
    Projectile: VL.FixedString = VL.FixedString
    Radius: VL.ConstantInt = VL.ConstantInt
    RemoveConditions: VL.Conditions = VL.Conditions
    RemoveEvents: VL.StatusEvent = VL.StatusEvent
    ResetCooldowns: VL.FixedString = VL.FixedString
    RetainSpells: VL.FixedString = VL.FixedString
    Rules: VL.Guid = VL.Guid
    Sheathing: VL.StatusSheathing = VL.StatusSheathing
    SoundLoop: VL.FixedString = VL.FixedString
    SoundStart: VL.FixedString = VL.FixedString
    SoundStop: VL.FixedString = VL.FixedString
    SoundVocalEnd: VL.SoundVocalType = VL.SoundVocalType
    SoundVocalLoop: VL.SoundVocalType = VL.SoundVocalType
    SoundVocalStart: VL.SoundVocalType = VL.SoundVocalType
    Spells: VL.FixedString = VL.FixedString
    SplatterBloodAmount: VL.ConstantFloat = VL.ConstantFloat
    SplatterDirtAmount: VL.ConstantFloat = VL.ConstantFloat
    SplatterSweatAmount: VL.ConstantFloat = VL.ConstantFloat
    StableRoll: VL.FixedString = VL.FixedString
    StableRollDC: VL.ConstantInt = VL.ConstantInt
    StackId: VL.FixedString = VL.FixedString
    StackPriority: VL.ConstantInt = VL.ConstantInt
    StackType: VL.StatusStackType = VL.StatusStackType
    StatsId: VL.FixedString = VL.FixedString
    StatusEffect: VL.FixedString = VL.FixedString
    StatusEffectOnTurn: VL.FixedString = VL.FixedString
    StatusEffectOverride: VL.FixedString = VL.FixedString
    StatusEffectOverrideForItems: VL.FixedString = VL.FixedString
    StatusGroups: VL.StatusGroupFlags = VL.StatusGroupFlags
    StatusPropertyFlags: VL.StatusPropertyFlags = VL.StatusPropertyFlags
    StatusSoundState: VL.FixedString = VL.FixedString
    StatusType: VL.FixedString = VL.FixedString
    StillAnimationPriority: VL.StillAnimPriority = VL.StillAnimPriority
    StillAnimationType: VL.StatusAnimationType = VL.StatusAnimationType
    SurfaceChange: VL.FixedString = VL.FixedString
    TargetConditions: VL.FixedString = VL.FixedString
    TargetEffect: VL.FixedString = VL.FixedString
    TemplateID: VL.FixedString = VL.FixedString
    TickFunctors: VL.StatsFunctors = VL.StatsFunctors
    TickType: VL.TickType = VL.TickType
    Toggle: VL.YesNo = VL.YesNo
    TooltipDamage: VL.FixedString = VL.FixedString
    TooltipPermanentWarnings: VL.FixedString = VL.FixedString
    TooltipSave: VL.FixedString = VL.FixedString
    UseLyingPickingState: VL.YesNo = VL.YesNo
    WeaponOverride: VL.FixedString = VL.FixedString


class Weapon(GameData):
    Boosts: VL.FixedString = VL.FixedString
    BoostsOnEquipMainHand: VL.FixedString = VL.FixedString
    BoostsOnEquipOffHand: VL.FixedString = VL.FixedString
    Charges: VL.ConstantInt = VL.ConstantInt
    ColorPresetResource: VL.FixedString = VL.FixedString
    ComboCategory: VL.FixedString = VL.FixedString
    Damage: VL.FixedString = VL.FixedString
    Damage_Range: VL.ConstantInt = VL.ConstantInt
    Damage_Type: VL.DamageType = VL.DamageType
    DefaultBoosts: VL.FixedString = VL.FixedString
    Durability: VL.ConstantInt = VL.ConstantInt
    DurabilityDegradeSpeed: VL.Qualifier = VL.Qualifier
    ExtraProperties: VL.FixedString = VL.FixedString
    FallingHitEffect: VL.FixedString = VL.FixedString
    FallingLandEffect: VL.FixedString = VL.FixedString
    Flags: VL.AttributeFlags = VL.AttributeFlags
    GameSize: VL.FixedString = VL.FixedString
    IgnoreVisionBlock: VL.YesNo = VL.YesNo
    InventoryTab: VL.InventoryTabs = VL.InventoryTabs
    ItemColor: VL.FixedString = VL.FixedString
    ItemGroup: VL.FixedString = VL.FixedString
    Level: VL.ConstantInt = VL.ConstantInt
    MaxAmount: VL.ConstantInt = VL.ConstantInt
    MaxCharges: VL.ConstantInt = VL.ConstantInt
    MaxLevel: VL.ConstantInt = VL.ConstantInt
    MinAmount: VL.ConstantInt = VL.ConstantInt
    MinLevel: VL.ConstantInt = VL.ConstantInt
    NeedsIdentification: VL.YesNo = VL.YesNo
    ObjectCategory: VL.FixedString = VL.FixedString
    PassivesMainHand: VL.FixedString = VL.FixedString
    PassivesOffHand: VL.FixedString = VL.FixedString
    PassivesOnEquip: VL.FixedString = VL.FixedString
    PersonalStatusImmunities: VL.StatusIDs = VL.StatusIDs
    Priority: VL.ConstantInt = VL.ConstantInt
    Proficiency_Group: VL.ProficiencyGroupFlags = VL.ProficiencyGroupFlags
    Projectile: VL.FixedString = VL.FixedString
    Rarity: VL.Rarity = VL.Rarity
    Requirements: VL.Requirements = VL.Requirements
    RootTemplate: VL.FixedString = VL.FixedString
    Slot: VL.Itemslot = VL.Itemslot
    SoundSize: VL.FixedString = VL.FixedString
    Spells: VL.FixedString = VL.FixedString
    StatusInInventory: VL.FixedString = VL.FixedString
    StatusOnEquip: VL.FixedString = VL.FixedString
    SupplyValue: VL.ConstantInt = VL.ConstantInt
    Tags: VL.FixedString = VL.FixedString
    Unique: VL.ConstantInt = VL.ConstantInt
    UniqueWeaponSoundSwitch: VL.FixedString = VL.FixedString
    UseConditions: VL.Conditions = VL.Conditions
    UseCosts: VL.FixedString = VL.FixedString
    ValueLevel: VL.ConstantInt = VL.ConstantInt
    ValueOverride: VL.ConstantInt = VL.ConstantInt
    ValueRounding: VL.ConstantInt = VL.ConstantInt
    ValueScale: VL.ConstantFloat = VL.ConstantFloat
    ValueUUID: VL.Guid = VL.Guid
    VersatileDamage: VL.FixedString = VL.FixedString
    WeaponFunctors: VL.StatsFunctors = VL.StatsFunctors
    WeaponRange: VL.ConstantInt = VL.ConstantInt
    Weapon_Group: VL.WeaponGroup = VL.WeaponGroup
    Weapon_Properties: VL.WeaponFlags = VL.WeaponFlags
    Weight: VL.ConstantFloat = VL.ConstantFloat
