#!/usr/bin/env python3
"""
The prologues for Baldur's Gate 3 mod files.
"""

import __main__
import os

_script = os.path.basename(__main__.__file__)
_prologue = f"DO NOT EDIT: This file was automatically generated by {_script}"

LUA_PROLOGUE = f"""\
-- {_prologue}

"""

PYTHON_PROLOGUE = f"""\
#!/usr/bin/env python3
# {_prologue}
"""

TXT_PROLOGUE = f"""\
// {_prologue}

"""

XML_PROLOGUE = bytes(f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!-- {_prologue} -->
""", "UTF-8")
