#!/usr/bin/env python3
"""
The prologues for Baldur's Gate 3 mod files.
"""

import __main__
import os

_script = os.path.basename(__main__.__file__)

XML_PROLOGUE = bytes(f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT: This file was automatically generated by {_script} -->
""", "UTF-8")
