#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata.valuelists as VL

from modtools.gamedata.gamedata import GameData


class Armor(GameData):
    Ability_Modifier_Cap: VL.ConstantInt = VL.ConstantInt
    ArmorClass: VL.ConstantInt = VL.ConstantInt
    ArmorType: VL.ArmorType = VL.ArmorType
    Armor_Class_Ability: VL.Ability = VL.Ability
    Boosts: VL.FixedString = VL.FixedString
    Charges: VL.ConstantInt = VL.ConstantInt
    ColorPresetResource: VL.FixedString = VL.FixedString
    ComboCategory: VL.FixedString = VL.FixedString
    DefaultBoosts: VL.FixedString = VL.FixedString
    Durability: VL.ConstantInt = VL.ConstantInt
    DurabilityDegradeSpeed: VL.Qualifier = VL.Qualifier
    ExtraProperties: VL.FixedString = VL.FixedString
    FallingHitEffect: VL.FixedString = VL.FixedString
    FallingLandEffect: VL.FixedString = VL.FixedString
    Flags: VL.AttributeFlags = VL.AttributeFlags
    GameSize: VL.FixedString = VL.FixedString
    InstrumentType: VL.InstrumentType = VL.InstrumentType
    InventoryTab: VL.InventoryTabs = VL.InventoryTabs
    ItemColor: VL.FixedString = VL.FixedString
    ItemGroup: VL.FixedString = VL.FixedString
    Level: VL.ConstantInt = VL.ConstantInt
    MaxAmount: VL.ConstantInt = VL.ConstantInt
    MaxCharges: VL.ConstantInt = VL.ConstantInt
    MaxLevel: VL.ConstantInt = VL.ConstantInt
    MinAmount: VL.ConstantInt = VL.ConstantInt
    MinLevel: VL.ConstantInt = VL.ConstantInt
    NeedsIdentification: VL.YesNo = VL.YesNo
    ObjectCategory: VL.FixedString = VL.FixedString
    PassivesOnEquip: VL.FixedString = VL.FixedString
    PersonalStatusImmunities: VL.StatusIDs = VL.StatusIDs
    Priority: VL.ConstantInt = VL.ConstantInt
    Proficiency_Group: VL.ProficiencyGroupFlags = VL.ProficiencyGroupFlags
    Rarity: VL.Rarity = VL.Rarity
    Requirements: VL.Requirements = VL.Requirements
    RootTemplate: VL.FixedString = VL.FixedString
    Shield: VL.YesNo = VL.YesNo
    Slot: VL.Itemslot = VL.Itemslot
    SoundSize: VL.FixedString = VL.FixedString
    Spells: VL.FixedString = VL.FixedString
    StatusInInventory: VL.FixedString = VL.FixedString
    StatusOnEquip: VL.FixedString = VL.FixedString
    Tags: VL.FixedString = VL.FixedString
    Unique: VL.ConstantInt = VL.ConstantInt
    UseConditions: VL.Conditions = VL.Conditions
    UseCosts: VL.FixedString = VL.FixedString
    ValueLevel: VL.ConstantInt = VL.ConstantInt
    ValueOverride: VL.ConstantInt = VL.ConstantInt
    ValueRounding: VL.ConstantInt = VL.ConstantInt
    ValueScale: VL.ConstantFloat = VL.ConstantFloat
    ValueUUID: VL.Guid = VL.Guid
    Weight: VL.ConstantFloat = VL.ConstantFloat

    def filename(self) -> str:
        return "Armor.txt"
