#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata.valuelists as VL

from modtools.gamedata.gamedata import GameData


class Character(GameData):
    AcidResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ActionResources: VL.FixedString = VL.FixedString
    Armor: VL.ConstantInt = VL.ConstantInt
    ArmorType: VL.ArmorType = VL.ArmorType
    BludgeoningResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Charisma: VL.ConstantInt = VL.ConstantInt
    Class: VL.FixedString = VL.FixedString
    ColdResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Constitution: VL.ConstantInt = VL.ConstantInt
    DarkvisionRange: VL.FixedString = VL.FixedString
    DefaultBoosts: VL.FixedString = VL.FixedString
    Dexterity: VL.ConstantInt = VL.ConstantInt
    DifficultyStatuses: VL.FixedString = VL.FixedString
    DynamicAnimationTag: VL.Guid = VL.Guid
    ExtraProperties: VL.FixedString = VL.FixedString
    FOV: VL.ConstantInt = VL.ConstantInt
    FallingHitEffect: VL.FixedString = VL.FixedString
    FallingLandEffect: VL.FixedString = VL.FixedString
    FireResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Flags: VL.AttributeFlags = VL.AttributeFlags
    ForceResistance: VL.ResistanceFlags = VL.ResistanceFlags
    GameSize: VL.FixedString = VL.FixedString
    Hearing: VL.ConstantInt = VL.ConstantInt
    Initiative: VL.ConstantInt = VL.ConstantInt
    Intelligence: VL.ConstantInt = VL.ConstantInt
    Level: VL.ConstantInt = VL.ConstantInt
    LightningResistance: VL.ResistanceFlags = VL.ResistanceFlags
    MinimumDetectionRange: VL.FixedString = VL.FixedString
    NecroticResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Passives: VL.FixedString = VL.FixedString
    PathInfluence: VL.FixedString = VL.FixedString
    PersonalStatusImmunities: VL.StatusIDs = VL.StatusIDs
    PiercingResistance: VL.ResistanceFlags = VL.ResistanceFlags
    PoisonResistance: VL.ResistanceFlags = VL.ResistanceFlags
    ProficiencyBonus: VL.ConstantInt = VL.ConstantInt
    ProficiencyBonusScaling: VL.Guid = VL.Guid
    Proficiency_Group: VL.ProficiencyGroupFlags = VL.ProficiencyGroupFlags
    Progression_Type: VL.ProgressionType = VL.ProgressionType
    Progressions: VL.FixedString = VL.FixedString
    PsychicResistance: VL.ResistanceFlags = VL.ResistanceFlags
    RadiantResistance: VL.ResistanceFlags = VL.ResistanceFlags
    Sight: VL.ConstantInt = VL.ConstantInt
    SlashingResistance: VL.ResistanceFlags = VL.ResistanceFlags
    SoundSize: VL.FixedString = VL.FixedString
    SpellCastingAbility: VL.Ability = VL.Ability
    StepsType: VL.StepsType = VL.StepsType
    Strength: VL.ConstantInt = VL.ConstantInt
    ThunderResistance: VL.ResistanceFlags = VL.ResistanceFlags
    UnarmedAttackAbility: VL.Ability = VL.Ability
    UnarmedRangedAttackAbility: VL.Ability = VL.Ability
    VerticalFOV: VL.ConstantInt = VL.ConstantInt
    Vitality: VL.ConstantInt = VL.ConstantInt
    Weight: VL.ConstantFloat = VL.ConstantFloat
    Wisdom: VL.ConstantInt = VL.ConstantInt
    XPReward: VL.Guid = VL.Guid

    def filename(self) -> str:
        return "Character.txt"
