#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata.valuelists as VL

from modtools.gamedata.gamedata import GameData


class CriticalHitTypeData(GameData):
    AcidFX: VL.Guid = VL.Guid
    BludgeoningFX: VL.Guid = VL.Guid
    ColdFX: VL.Guid = VL.Guid
    FireFX: VL.Guid = VL.Guid
    ForceFX: VL.Guid = VL.Guid
    LightningFX: VL.Guid = VL.Guid
    NecroticFX: VL.Guid = VL.Guid
    PiercingFX: VL.Guid = VL.Guid
    PoisonFX: VL.Guid = VL.Guid
    PsychicFX: VL.Guid = VL.Guid
    RadiantFX: VL.Guid = VL.Guid
    SlashingFX: VL.Guid = VL.Guid
    ThunderFX: VL.Guid = VL.Guid

    def __init__(self,
                 name: str,
                 *,
                 using: str = None,
                 AcidFX: VL.Guid = None,
                 BludgeoningFX: VL.Guid = None,
                 ColdFX: VL.Guid = None,
                 FireFX: VL.Guid = None,
                 ForceFX: VL.Guid = None,
                 LightningFX: VL.Guid = None,
                 NecroticFX: VL.Guid = None,
                 PiercingFX: VL.Guid = None,
                 PoisonFX: VL.Guid = None,
                 PsychicFX: VL.Guid = None,
                 RadiantFX: VL.Guid = None,
                 SlashingFX: VL.Guid = None,
                 ThunderFX: VL.Guid = None):
        self.name = name
        self.using = using
        self.AcidFX = AcidFX
        self.BludgeoningFX = BludgeoningFX
        self.ColdFX = ColdFX
        self.FireFX = FireFX
        self.ForceFX = ForceFX
        self.LightningFX = LightningFX
        self.NecroticFX = NecroticFX
        self.PiercingFX = PiercingFX
        self.PoisonFX = PoisonFX
        self.PsychicFX = PsychicFX
        self.RadiantFX = RadiantFX
        self.SlashingFX = SlashingFX
        self.ThunderFX = ThunderFX

    def filename(self) -> str:
        return "CriticalHitTypes.txt"
