#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata.valuelists as VL

from modtools.gamedata.gamedata import GameData


class InterruptData(GameData):
    Conditions: VL.Conditions = VL.Conditions
    Container: VL.FixedString = VL.FixedString
    Cooldown: VL.CooldownType = VL.CooldownType
    Cost: VL.FixedString = VL.FixedString
    Description: VL.TranslatedString = VL.TranslatedString
    DescriptionParams: VL.FixedString = VL.FixedString
    DescriptionRef: VL.TranslatedString = VL.TranslatedString
    DisplayName: VL.TranslatedString = VL.TranslatedString
    DisplayNameRef: VL.TranslatedString = VL.TranslatedString
    EnableCondition: VL.Conditions = VL.Conditions
    EnableContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ExtraDescription: VL.TranslatedString = VL.TranslatedString
    ExtraDescriptionParams: VL.FixedString = VL.FixedString
    ExtraDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Failure: VL.StatsFunctors = VL.StatsFunctors
    Icon: VL.FixedString = VL.FixedString
    InterruptContext: VL.InterruptContext = VL.InterruptContext
    InterruptContextScope: VL.InterruptContextScope = VL.InterruptContextScope
    InterruptDefaultValue: VL.InterruptDefaultValue = VL.InterruptDefaultValue
    InterruptFlags: VL.InterruptFlagsList = VL.InterruptFlagsList
    LoreDescription: VL.TranslatedString = VL.TranslatedString
    LoreDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Properties: VL.StatsFunctors = VL.StatsFunctors
    Roll: VL.Conditions = VL.Conditions
    ShortDescription: VL.TranslatedString = VL.TranslatedString
    ShortDescriptionParams: VL.FixedString = VL.FixedString
    ShortDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Stack: VL.FixedString = VL.FixedString
    Success: VL.StatsFunctors = VL.StatsFunctors
    TooltipAttackSave: VL.FixedString = VL.FixedString
    TooltipDamageList: VL.FixedString = VL.FixedString
    TooltipOnMiss: VL.FixedString = VL.FixedString
    TooltipOnSave: VL.FixedString = VL.FixedString
    TooltipPermanentWarnings: VL.FixedString = VL.FixedString
    TooltipStatusApply: VL.FixedString = VL.FixedString

    def __init__(self,
                 name: str,
                 *,
                 using: str = None,
                 Conditions: VL.Conditions = None,
                 Container: VL.FixedString = None,
                 Cooldown: VL.CooldownType = None,
                 Cost: VL.FixedString = None,
                 Description: VL.TranslatedString = None,
                 DescriptionParams: VL.FixedString = None,
                 DescriptionRef: VL.TranslatedString = None,
                 DisplayName: VL.TranslatedString = None,
                 DisplayNameRef: VL.TranslatedString = None,
                 EnableCondition: VL.Conditions = None,
                 EnableContext: VL.StatsFunctorContext = None,
                 ExtraDescription: VL.TranslatedString = None,
                 ExtraDescriptionParams: VL.FixedString = None,
                 ExtraDescriptionRef: VL.TranslatedString = None,
                 Failure: VL.StatsFunctors = None,
                 Icon: VL.FixedString = None,
                 InterruptContext: VL.InterruptContext = None,
                 InterruptContextScope: VL.InterruptContextScope = None,
                 InterruptDefaultValue: VL.InterruptDefaultValue = None,
                 InterruptFlags: VL.InterruptFlagsList = None,
                 LoreDescription: VL.TranslatedString = None,
                 LoreDescriptionRef: VL.TranslatedString = None,
                 Properties: VL.StatsFunctors = None,
                 Roll: VL.Conditions = None,
                 ShortDescription: VL.TranslatedString = None,
                 ShortDescriptionParams: VL.FixedString = None,
                 ShortDescriptionRef: VL.TranslatedString = None,
                 Stack: VL.FixedString = None,
                 Success: VL.StatsFunctors = None,
                 TooltipAttackSave: VL.FixedString = None,
                 TooltipDamageList: VL.FixedString = None,
                 TooltipOnMiss: VL.FixedString = None,
                 TooltipOnSave: VL.FixedString = None,
                 TooltipPermanentWarnings: VL.FixedString = None,
                 TooltipStatusApply: VL.FixedString = None):
        self.name = name
        self.using = using
        self.Conditions = Conditions
        self.Container = Container
        self.Cooldown = Cooldown
        self.Cost = Cost
        self.Description = Description
        self.DescriptionParams = DescriptionParams
        self.DescriptionRef = DescriptionRef
        self.DisplayName = DisplayName
        self.DisplayNameRef = DisplayNameRef
        self.EnableCondition = EnableCondition
        self.EnableContext = EnableContext
        self.ExtraDescription = ExtraDescription
        self.ExtraDescriptionParams = ExtraDescriptionParams
        self.ExtraDescriptionRef = ExtraDescriptionRef
        self.Failure = Failure
        self.Icon = Icon
        self.InterruptContext = InterruptContext
        self.InterruptContextScope = InterruptContextScope
        self.InterruptDefaultValue = InterruptDefaultValue
        self.InterruptFlags = InterruptFlags
        self.LoreDescription = LoreDescription
        self.LoreDescriptionRef = LoreDescriptionRef
        self.Properties = Properties
        self.Roll = Roll
        self.ShortDescription = ShortDescription
        self.ShortDescriptionParams = ShortDescriptionParams
        self.ShortDescriptionRef = ShortDescriptionRef
        self.Stack = Stack
        self.Success = Success
        self.TooltipAttackSave = TooltipAttackSave
        self.TooltipDamageList = TooltipDamageList
        self.TooltipOnMiss = TooltipOnMiss
        self.TooltipOnSave = TooltipOnSave
        self.TooltipPermanentWarnings = TooltipPermanentWarnings
        self.TooltipStatusApply = TooltipStatusApply

    def filename(self) -> str:
        return "Interrupt.txt"
