#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata.valuelists as VL

from modtools.gamedata.gamedata import GameData


class InterruptData(GameData):
    Conditions: VL.Conditions = VL.Conditions
    Container: VL.FixedString = VL.FixedString
    Cooldown: VL.CooldownType = VL.CooldownType
    Cost: VL.FixedString = VL.FixedString
    Description: VL.TranslatedString = VL.TranslatedString
    DescriptionParams: VL.FixedString = VL.FixedString
    DescriptionRef: VL.TranslatedString = VL.TranslatedString
    DisplayName: VL.TranslatedString = VL.TranslatedString
    DisplayNameRef: VL.TranslatedString = VL.TranslatedString
    EnableCondition: VL.Conditions = VL.Conditions
    EnableContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ExtraDescription: VL.TranslatedString = VL.TranslatedString
    ExtraDescriptionParams: VL.FixedString = VL.FixedString
    ExtraDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Failure: VL.StatsFunctors = VL.StatsFunctors
    Icon: VL.FixedString = VL.FixedString
    InterruptContext: VL.InterruptContext = VL.InterruptContext
    InterruptContextScope: VL.InterruptContextScope = VL.InterruptContextScope
    InterruptDefaultValue: VL.InterruptDefaultValue = VL.InterruptDefaultValue
    InterruptFlags: VL.InterruptFlagsList = VL.InterruptFlagsList
    LoreDescription: VL.TranslatedString = VL.TranslatedString
    LoreDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Properties: VL.StatsFunctors = VL.StatsFunctors
    Roll: VL.Conditions = VL.Conditions
    ShortDescription: VL.TranslatedString = VL.TranslatedString
    ShortDescriptionParams: VL.FixedString = VL.FixedString
    ShortDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Stack: VL.FixedString = VL.FixedString
    Success: VL.StatsFunctors = VL.StatsFunctors
    TooltipAttackSave: VL.FixedString = VL.FixedString
    TooltipDamageList: VL.FixedString = VL.FixedString
    TooltipOnMiss: VL.FixedString = VL.FixedString
    TooltipOnSave: VL.FixedString = VL.FixedString
    TooltipPermanentWarnings: VL.FixedString = VL.FixedString
    TooltipStatusApply: VL.FixedString = VL.FixedString

    def filename(self) -> str:
        return "Interrupt.txt"
