#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata.valuelists as VL

from modtools.gamedata.gamedata import GameData


class PassiveData(GameData):
    BoostConditions: VL.Conditions = VL.Conditions
    BoostContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    Boosts: VL.FixedString = VL.FixedString
    Conditions: VL.Conditions = VL.Conditions
    Description: VL.TranslatedString = VL.TranslatedString
    DescriptionParams: VL.FixedString = VL.FixedString
    DescriptionRef: VL.TranslatedString = VL.TranslatedString
    DisplayName: VL.TranslatedString = VL.TranslatedString
    DisplayNameRef: VL.TranslatedString = VL.TranslatedString
    DynamicAnimationTag: VL.Guid = VL.Guid
    EnabledConditions: VL.Conditions = VL.Conditions
    EnabledContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ExtraDescription: VL.TranslatedString = VL.TranslatedString
    ExtraDescriptionParams: VL.FixedString = VL.FixedString
    ExtraDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Icon: VL.FixedString = VL.FixedString
    LoreDescription: VL.TranslatedString = VL.TranslatedString
    LoreDescriptionRef: VL.TranslatedString = VL.TranslatedString
    PriorityOrder: VL.ConstantInt = VL.ConstantInt
    Properties: VL.PassiveFlags = VL.PassiveFlags
    StatsFunctorContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    StatsFunctors: VL.StatsFunctors = VL.StatsFunctors
    ToggleGroup: VL.FixedString = VL.FixedString
    ToggleOffContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ToggleOffEffect: VL.FixedString = VL.FixedString
    ToggleOffFunctors: VL.StatsFunctors = VL.StatsFunctors
    ToggleOnEffect: VL.FixedString = VL.FixedString
    ToggleOnFunctors: VL.StatsFunctors = VL.StatsFunctors
    TooltipConditionalDamage: VL.FixedString = VL.FixedString
    TooltipPermanentWarnings: VL.FixedString = VL.FixedString
    TooltipSave: VL.FixedString = VL.FixedString
    TooltipUseCosts: VL.FixedString = VL.FixedString

    def filename(self) -> str:
        return "Passive.txt"
