#!/usr/bin/env python3
# DO NOT EDIT: This file was automatically generated by GameDataParser.py

import modtools.gamedata.valuelists as VL

from modtools.gamedata.gamedata import GameData


class PassiveData(GameData):
    BoostConditions: VL.Conditions = VL.Conditions
    BoostContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    Boosts: VL.FixedString = VL.FixedString
    Conditions: VL.Conditions = VL.Conditions
    Description: VL.TranslatedString = VL.TranslatedString
    DescriptionParams: VL.FixedString = VL.FixedString
    DescriptionRef: VL.TranslatedString = VL.TranslatedString
    DisplayName: VL.TranslatedString = VL.TranslatedString
    DisplayNameRef: VL.TranslatedString = VL.TranslatedString
    DynamicAnimationTag: VL.Guid = VL.Guid
    EnabledConditions: VL.Conditions = VL.Conditions
    EnabledContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ExtraDescription: VL.TranslatedString = VL.TranslatedString
    ExtraDescriptionParams: VL.FixedString = VL.FixedString
    ExtraDescriptionRef: VL.TranslatedString = VL.TranslatedString
    Icon: VL.FixedString = VL.FixedString
    LoreDescription: VL.TranslatedString = VL.TranslatedString
    LoreDescriptionRef: VL.TranslatedString = VL.TranslatedString
    PriorityOrder: VL.ConstantInt = VL.ConstantInt
    Properties: VL.PassiveFlags = VL.PassiveFlags
    StatsFunctorContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    StatsFunctors: VL.StatsFunctors = VL.StatsFunctors
    ToggleGroup: VL.FixedString = VL.FixedString
    ToggleOffContext: VL.StatsFunctorContext = VL.StatsFunctorContext
    ToggleOffEffect: VL.FixedString = VL.FixedString
    ToggleOffFunctors: VL.StatsFunctors = VL.StatsFunctors
    ToggleOnEffect: VL.FixedString = VL.FixedString
    ToggleOnFunctors: VL.StatsFunctors = VL.StatsFunctors
    TooltipConditionalDamage: VL.FixedString = VL.FixedString
    TooltipPermanentWarnings: VL.FixedString = VL.FixedString
    TooltipSave: VL.FixedString = VL.FixedString
    TooltipUseCosts: VL.FixedString = VL.FixedString

    def __init__(self,
                 name: str,
                 *,
                 using: str = None,
                 BoostConditions: VL.Conditions = None,
                 BoostContext: VL.StatsFunctorContext = None,
                 Boosts: VL.FixedString = None,
                 Conditions: VL.Conditions = None,
                 Description: VL.TranslatedString = None,
                 DescriptionParams: VL.FixedString = None,
                 DescriptionRef: VL.TranslatedString = None,
                 DisplayName: VL.TranslatedString = None,
                 DisplayNameRef: VL.TranslatedString = None,
                 DynamicAnimationTag: VL.Guid = None,
                 EnabledConditions: VL.Conditions = None,
                 EnabledContext: VL.StatsFunctorContext = None,
                 ExtraDescription: VL.TranslatedString = None,
                 ExtraDescriptionParams: VL.FixedString = None,
                 ExtraDescriptionRef: VL.TranslatedString = None,
                 Icon: VL.FixedString = None,
                 LoreDescription: VL.TranslatedString = None,
                 LoreDescriptionRef: VL.TranslatedString = None,
                 PriorityOrder: VL.ConstantInt = None,
                 Properties: VL.PassiveFlags = None,
                 StatsFunctorContext: VL.StatsFunctorContext = None,
                 StatsFunctors: VL.StatsFunctors = None,
                 ToggleGroup: VL.FixedString = None,
                 ToggleOffContext: VL.StatsFunctorContext = None,
                 ToggleOffEffect: VL.FixedString = None,
                 ToggleOffFunctors: VL.StatsFunctors = None,
                 ToggleOnEffect: VL.FixedString = None,
                 ToggleOnFunctors: VL.StatsFunctors = None,
                 TooltipConditionalDamage: VL.FixedString = None,
                 TooltipPermanentWarnings: VL.FixedString = None,
                 TooltipSave: VL.FixedString = None,
                 TooltipUseCosts: VL.FixedString = None):
        self.name = name
        self.using = using
        self.BoostConditions = BoostConditions
        self.BoostContext = BoostContext
        self.Boosts = Boosts
        self.Conditions = Conditions
        self.Description = Description
        self.DescriptionParams = DescriptionParams
        self.DescriptionRef = DescriptionRef
        self.DisplayName = DisplayName
        self.DisplayNameRef = DisplayNameRef
        self.DynamicAnimationTag = DynamicAnimationTag
        self.EnabledConditions = EnabledConditions
        self.EnabledContext = EnabledContext
        self.ExtraDescription = ExtraDescription
        self.ExtraDescriptionParams = ExtraDescriptionParams
        self.ExtraDescriptionRef = ExtraDescriptionRef
        self.Icon = Icon
        self.LoreDescription = LoreDescription
        self.LoreDescriptionRef = LoreDescriptionRef
        self.PriorityOrder = PriorityOrder
        self.Properties = Properties
        self.StatsFunctorContext = StatsFunctorContext
        self.StatsFunctors = StatsFunctors
        self.ToggleGroup = ToggleGroup
        self.ToggleOffContext = ToggleOffContext
        self.ToggleOffEffect = ToggleOffEffect
        self.ToggleOffFunctors = ToggleOffFunctors
        self.ToggleOnEffect = ToggleOnEffect
        self.ToggleOnFunctors = ToggleOnFunctors
        self.TooltipConditionalDamage = TooltipConditionalDamage
        self.TooltipPermanentWarnings = TooltipPermanentWarnings
        self.TooltipSave = TooltipSave
        self.TooltipUseCosts = TooltipUseCosts

    def filename(self) -> str:
        return "Passive.txt"
